

baseURL: https://joelmerki-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Joël Merki
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Welcome to my portfolio website, where you can get to know me and the work I have done as part of the Masters in Analytics and Management at LBS.
    title: Hi, my name is Joël
  blog: {}
  contact:
    address:
      - city: London, W1U 4HH
        country: United Kingdom
        street: 39 Paddington Street 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jmerki.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +41 79 957 60 01 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Joël Merki
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/JoelMerki?tab=repositories
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jo%C3%ABl-merki/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: All blogs
        url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs
      # - name: Generic Blog
      #   url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: LBS MAM '23
    title: Joël Merki
  tiles:
    enable: yes
    showcase:
      - image: Glacier.jpg
        subtitle: A short introduction to my experiences and interests
        title: About me
        url: blogs/about_me
      - image: London_bikes.jpg
        subtitle: Analysis of TfL bike rentals over the past years
        title: TfL bike rental analysis
        url: blogs/bike
      - image: Climate_change.jpg
        subtitle: Analysis of climate change and temperature anomalies
        title: Climate change and temperature anomalies
        url: blogs/climate
      - image: Omega.jpg
        subtitle: Exploring differences between the salaries of men and women working at Omega
        title: Omega Group - Pay Discrimination 
        url: blogs/omega
      # - image: pic05.jpg
      #   subtitle: Ipsum Dolor Sit Amet
      #   title: Consequat
      #   url: blogs/ipsum
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Etiam
      #   url: blogs/ipsum
  two:
    buttonText: Click here
    enable: yes
    subtitle: "If you ever struggle to explain normal distribution to someone, just show them the below."
    title: Real life example of Normal distribution
    url: https://twitter.com/NunoClara_/status/1571142901870268417?s=20&t=A972oDsKVLwRZGm8bUp7Cw
